name: Hello GitHub Actions

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: company-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Self-Hosted Runner!!"
